### ISSUE TITLE
Homebridge error "Cannot update reachability on non-bridged accessory!"

### ISSUE THREAD

**Issue by optimus-bret** [MortJC/homebridge-platform-orbit#2]
I just installed homebridge-platform-orbit. I add the platform to config.js (as noted in README.md). At runtime I am seeing the error:

```
Unhandled rejection Error: Cannot update reachability on non-bridged accessory!
    at Accessory.updateReachability (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:254:11)
    at PlatformOrbit._createIrrigationAccessory (/usr/local/lib/node_modules/homebridge-platform-orbit/platform.js:112:18)
```
This appears to be when an Acceessory is being added using Service.IrrigationSystem

**Comment by MortJC** [comment]
Looks like updateReachability has been deprecated and is not required. I've removed it and updated the package. Let me know if it work for you now.

**Comment by optimus-bret** [comment]
Thanks for the update @MortJC.

I just installed it, now I get this in stderror:

Unhandled rejection Error: homebridge-platform-orbit - orbit attempt to register an accessory that isn't PlatformAccessory!
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:165:13)
    at PlatformOrbit.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-orbit/platform.js:84:26)
    at Array.forEach (<anonymous>)
    at PlatformOrbit.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-orbit/platform.js:46:21)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

**Comment by optimus-bret** [comment]
The call to registerPlatformAccessories expects an array of PlatformAccessory objects.

Did they change this recently on you? I am using the latest homebridge which is at version 0.4.50

Bret

**Comment by MortJC** [comment]
Think the issue is the global variables are conflicting with something else you are running. I've removed the global reference and renamed Accessory to PlatformAccessory.

**Comment by optimus-bret** [comment]
Works!
Thx
